# Generated by Django 5.0.4 on 2024-06-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_weatherforecast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherForecast',
        ),
    ]
