# Generated by Django 5.0.4 on 2024-06-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_weatherforecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherforecast',
            old_name='pressure',
            new_name='precipitation',
        ),
    ]
