# Generated by Django 5.0.4 on 2024-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_migrate_unique_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquebrands',
            name='brand_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
