# Generated by Django 5.0.4 on 2024-06-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
    ]
