# Generated by Django 5.0.4 on 2024-06-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_smartphone'),
    ]

    operations = [
    ]
