# Generated by Django 5.0.4 on 2024-06-23 16:37
from datetime import timedelta

from django.db import migrations


def set_delivery_warranty(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')

    for order in Order.objects.all():
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = "24 months"
            order.save()
        elif order.status == 'Cancelled':
            order.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0017_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_warranty)
    ]
