"""Added file to the song model

Revision ID: 041ef5eab01b
Revises: 3f832284d893
Create Date: 2024-08-07 14:19:47.849798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041ef5eab01b'
down_revision: Union[str, None] = '3f832284d893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('music_file_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'music_file_data')
    # ### end Alembic commands ###
