# Generated by Django 5.0.4 on 2024-07-08 09:02

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_owner', models.CharField(max_length=100)),
                ('card_number', main_app.models.MaskedCreditCardField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=main_app.models.StudentIDField(validators=[main_app.models.StudentIDField.validate_student_id]),
        ),
    ]
